export const ADD_NOTE = 'NOTE/ADD';
export const SEARCH_NOTE = 'NOTE/SEARCH';
export const UPDATE_NOTE = 'NOTE/UPDATE';
export const DELETE_NOTE = 'NOTE/DELETE';

export const ADD_STARTED = 'NOTE/ADD_STARTED';
export const ADD_SUCCESS = 'NOTE/ADD_SUCCESS';
export const ADD_FAILURE = 'NOTE/ADD_FAILURE';

export const VIEW_STARTED = 'NOTE/VIEW_STARTED';
export const VIEW_SUCCESS = 'NOTE/VIEW_SUCCESS';
export const VIEW_FAILURE = 'NOTE/VIEW_FAILURE';

export const SEARCH_STARTED = 'NOTE/SEARCH_STARTED';
export const SEARCH_SUCCESS = 'NOTE/SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'NOTE/SEARCH_FAILURE';

export const UPDATE_STARTED = 'NOTE/UPDATE_STARTED';
export const UPDATE_SUCCESS = 'NOTE/UPDATE_SUCCESS';
export const UPDATE_FAILURE = 'NOTE/UPDATE_FAILURE';

export const DELETE_STARTED = 'NOTE/DELETE_STARTED';
export const DELETE_SUCCESS = 'NOTE/DELETE_SUCCESS';
export const DELETE_FAILURE = 'NOTE/DELETE_FAILURE';